spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Firengiz77
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
 secret: S3cR3t_K3y!gklD90$5h&4df!
 expiration: 86400000  # 24 hours
server:
  port: 8081
doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
